version: '3.8'

services:
  orchestrator-py:
    container_name: orchestrator-py
    build:
      context: ./backend/orchestrator-py
    volumes:
      - ./backend/orchestrator-py:/app
    networks:
      - llm-network

  gateway-go:
    container_name: gateway-go
    build:
      context: ./backend/gateway-go
    volumes:
      - ./backend/gateway-go:/app
    networks:
      - llm-network

  api-gateway:
    container_name: api-gateway
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/api-gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge