quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=llm_user
quarkus.datasource.password=llm_password
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-db:5432/llm_identity_db

quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.log.sql=true

mp.jwt.verify.issuer=https://llm-remote-assistant.com

smallrye.jwt.sign.key.location=privateKey.pem

mp.jwt.verify.publickey.location=publicKey.pem
