// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.0
// source: backend/gateway-go/protos/orchestrator.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorServiceClient interface {
	ProcessCommand(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (OrchestratorService_ProcessCommandClient, error)
	HandleConfirmation(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) ProcessCommand(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (OrchestratorService_ProcessCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &OrchestratorService_ServiceDesc.Streams[0], "/orchestrator.OrchestratorService/ProcessCommand", opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorServiceProcessCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrchestratorService_ProcessCommandClient interface {
	Recv() (*ProcessResponse, error)
	grpc.ClientStream
}

type orchestratorServiceProcessCommandClient struct {
	grpc.ClientStream
}

func (x *orchestratorServiceProcessCommandClient) Recv() (*ProcessResponse, error) {
	m := new(ProcessResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orchestratorServiceClient) HandleConfirmation(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error) {
	out := new(ConfirmationResponse)
	err := c.cc.Invoke(ctx, "/orchestrator.OrchestratorService/HandleConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility
type OrchestratorServiceServer interface {
	ProcessCommand(*ProcessRequest, OrchestratorService_ProcessCommandServer) error
	HandleConfirmation(context.Context, *ConfirmationRequest) (*ConfirmationResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServiceServer struct {
}

func (UnimplementedOrchestratorServiceServer) ProcessCommand(*ProcessRequest, OrchestratorService_ProcessCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessCommand not implemented")
}
func (UnimplementedOrchestratorServiceServer) HandleConfirmation(context.Context, *ConfirmationRequest) (*ConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleConfirmation not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_ProcessCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServiceServer).ProcessCommand(m, &orchestratorServiceProcessCommandServer{stream})
}

type OrchestratorService_ProcessCommandServer interface {
	Send(*ProcessResponse) error
	grpc.ServerStream
}

type orchestratorServiceProcessCommandServer struct {
	grpc.ServerStream
}

func (x *orchestratorServiceProcessCommandServer) Send(m *ProcessResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _OrchestratorService_HandleConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).HandleConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orchestrator.OrchestratorService/HandleConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).HandleConfirmation(ctx, req.(*ConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleConfirmation",
			Handler:    _OrchestratorService_HandleConfirmation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessCommand",
			Handler:       _OrchestratorService_ProcessCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend/gateway-go/protos/orchestrator.proto",
}
