# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0corchestrator\"7\n\x0eProcessRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x13\n\x0bmessageJson\x18\x02 \x01(\t\"2\n\x0fProcessResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x13OrchestratorService\x12O\n\x0eProcessCommand\x12\x1c.orchestrator.ProcessRequest\x1a\x1d.orchestrator.ProcessResponse\"\x00\x42%Z#llm-remote-assistant/gateway/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#llm-remote-assistant/gateway/protos'
  _globals['_PROCESSREQUEST']._serialized_start=36
  _globals['_PROCESSREQUEST']._serialized_end=91
  _globals['_PROCESSRESPONSE']._serialized_start=93
  _globals['_PROCESSRESPONSE']._serialized_end=143
  _globals['_ORCHESTRATORSERVICE']._serialized_start=145
  _globals['_ORCHESTRATORSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
